version: '3.4'

services:
  paasui:
    image: repo.isw.la/paas-ui:${APP_VERSION}.${BUILD_NUMBER}
    ports:
      - "3000:80"
    network_mode: "host"
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - NEXT_PUBLIC_PASSPORT_BASE_URL=${NEXT_PUBLIC_PASSPORT_BASE_URL}
        - NEXT_PUBLIC_SECRET=${NEXT_PUBLIC_SECRET}
        - NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}
        - NEXT_PUBLIC_CURRENT_API_VERSION=${NEXT_PUBLIC_CURRENT_API_VERSION}
        - NEXT_PUBLIC_API_BASE_URL_ALTERNATIVE=${NEXT_PUBLIC_API_BASE_URL_ALTERNATIVE}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_ALLOWED_APPS=${NEXT_PUBLIC_ALLOWED_APPS}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
      dockerfile: ./Dockerfile
