version: '3.4'

services:
  passui:
    image: repo.isw.la/paas-ui:${APP_VERSION}.${BUILD_NUMBER}
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - NEXT_PUBLIC_PASSPORT_TOKEN_URL=${NEXT_PUBLIC_PASSPORT_TOKEN_URL}
        - NEXT_PUBLIC_CLIENT_ID=${NEXT_PUBLIC_CLIENT_ID}
        - NEXT_PUBLIC_SECRET=${NEXT_PUBLIC_SECRET}
        - NEXT_PUBLIC_GRANT_TYPE=${NEXT_PUBLIC_GRANT_TYPE}
        - NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}
        - NEXT_PUBLIC_PASSPORT_AUTHORIZE_URL=${NEXT_PUBLIC_PASSPORT_AUTHORIZE_URL}
        - NEXT_PUBLIC_RESPONSE_TYPE=${NEXT_PUBLIC_RESPONSE_TYPE}
        - NEXT_PUBLIC_SCOPE=${NEXT_PUBLIC_SCOPE}
        - NEXT_PUBLIC_PASSPORT_PROFILE_URL=${NEXT_PUBLIC_PASSPORT_PROFILE_URL}
        - NEXT_PUBLIC_CURRENT_API_VERSION=${NEXT_PUBLIC_CURRENT_API_VERSION}
        - NEXT_PUBLIC_API_BASE_URL_ALTERNATIVE=${NEXT_PUBLIC_API_BASE_URL_ALTERNATIVE}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - http_proxy=${http_proxy}
      dockerfile: ./Dockerfile
    ports:
      - 80:80
